version: "3.7"

services:
  airbnb:
    image: mongo
    container_name: airbnb-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=lordaction
      - MONGO_INITDB_ROOT_DATABASE=airbnb
    volumes:
      - /var/lib/db:/airbnb
